# Generated by Django 6.0.3 on 2026-04-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_create_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('completed', 'completed')], default='active', max_length=20),
        ),
    ]
