# Generated by Django 6.0.3 on 2026-07-10 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_tasks_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='resource_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
